// Try catch 

try {
    const a = 20;
    const b = 40;
    const c = a +
        console.log(c)
}
catch (err) {
    console.log('error')
}